# Generated by Django 5.0.6 on 2024-06-23 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="Enquiry",
        ),
        migrations.AlterModelOptions(
            name="enquiry",
            options={"verbose_name": "Enquiry List"},
        ),
        migrations.AlterModelTable(
            name="enquiry",
            table="Enquiry",
        ),
    ]
